#!/usr/bin/env python3

# Standard library imports
from random import randint, choice as rc

# Remote library imports
from faker import Faker

# Local imports
from app import app
from models import db, Card, User, Tag, Icon, UserIcon, UserTag

def create_cards():

    cards = []

    # Spades
    card1 = Card(name = "A", suit = "Spades", value = 1, image = "https://deckofcardsapi.com/static/img/AS.png")
    cards.append(card1)
    card2 = Card(name = "2", suit = "Spades", value = 2, image = "https://deckofcardsapi.com/static/img/2S.png")
    cards.append(card2)
    card3 = Card(name = "3", suit = "Spades", value = 3, image = "https://deckofcardsapi.com/static/img/3S.png")
    cards.append(card3)
    card4 = Card(name = "4", suit = "Spades", value = 4, image = "https://deckofcardsapi.com/static/img/4S.png")
    cards.append(card4)
    card5 = Card(name = "5", suit = "Spades", value = 5, image = "https://deckofcardsapi.com/static/img/5S.png")
    cards.append(card5)
    card6 = Card(name = "6", suit = "Spades", value = 6, image = "https://deckofcardsapi.com/static/img/6S.png")
    cards.append(card6)
    card7 = Card(name = "7", suit = "Spades", value = 7, image = "https://deckofcardsapi.com/static/img/7S.png")
    cards.append(card7)
    card8 = Card(name = "8", suit = "Spades", value = 8, image = "https://deckofcardsapi.com/static/img/8S.png")
    cards.append(card8)
    card9 = Card(name = "9", suit = "Spades", value = 9, image = "https://deckofcardsapi.com/static/img/9S.png")
    cards.append(card9)
    card10 = Card(name = "10", suit = "Spades", value = 10, image = "https://deckofcardsapi.com/static/img/0S.png")
    cards.append(card10)
    card11 = Card(name = "J", suit = "Spades", value = 11, image = "https://deckofcardsapi.com/static/img/JS.png")
    cards.append(card11)
    card12 = Card(name = "Q", suit = "Spades", value = 12, image = "https://deckofcardsapi.com/static/img/QS.png")
    cards.append(card12)
    card13 = Card(name = "K", suit = "Spades", value = 13, image = "https://deckofcardsapi.com/static/img/KS.png")
    cards.append(card12)

    # Hearts
    card14 = Card(name = "A", suit = "Hearts", value = 1, image = "https://deckofcardsapi.com/static/img/AH.png")
    cards.append(card14)
    card15 = Card(name = "2", suit = "Hearts", value = 2, image = "https://deckofcardsapi.com/static/img/2H.png")
    cards.append(card15)
    card16 = Card(name = "3", suit = "Hearts", value = 3, image = "https://deckofcardsapi.com/static/img/3H.png")
    cards.append(card16)
    card17 = Card(name = "4", suit = "Hearts", value = 4, image = "https://deckofcardsapi.com/static/img/4H.png")
    cards.append(card17)
    card18 = Card(name = "5", suit = "Hearts", value = 5, image = "https://deckofcardsapi.com/static/img/5H.png")
    cards.append(card18)
    card19 = Card(name = "6", suit = "Hearts", value = 6, image = "https://deckofcardsapi.com/static/img/6H.png")
    cards.append(card19)
    card20 = Card(name = "7", suit = "Hearts", value = 7, image = "https://deckofcardsapi.com/static/img/7H.png")
    cards.append(card20)
    card21 = Card(name = "8", suit = "Hearts", value = 8, image = "https://deckofcardsapi.com/static/img/8H.png")
    cards.append(card21)
    card22 = Card(name = "9", suit = "Hearts", value = 9, image = "https://deckofcardsapi.com/static/img/9H.png")
    cards.append(card22)
    card23 = Card(name = "10", suit = "Hearts", value = 10, image = "https://deckofcardsapi.com/static/img/0H.png")
    cards.append(card23)
    card24 = Card(name = "J", suit = "Hearts", value = 11, image = "https://deckofcardsapi.com/static/img/JH.png")
    cards.append(card24)
    card25 = Card(name = "Q", suit = "Hearts", value = 12, image = "https://deckofcardsapi.com/static/img/QH.png")
    cards.append(card25)
    card26 = Card(name = "K", suit = "Hearts", value = 13, image = "https://deckofcardsapi.com/static/img/KH.png")
    cards.append(card26)
    # Clubs
    card27 = Card(name = "A", suit = "Clubs", value = 1, image = "https://deckofcardsapi.com/static/img/AC.png")
    cards.append(card27)
    card28 = Card(name = "2", suit = "Clubs", value = 2, image = "https://deckofcardsapi.com/static/img/2C.png")
    cards.append(card28)
    card29 = Card(name = "3", suit = "Clubs", value = 3, image = "https://deckofcardsapi.com/static/img/3C.png")
    cards.append(card29)
    card30 = Card(name = "4", suit = "Clubs", value = 4, image = "https://deckofcardsapi.com/static/img/4C.png")
    cards.append(card30)
    card31 = Card(name = "5", suit = "Clubs", value = 5, image = "https://deckofcardsapi.com/static/img/5C.png")
    cards.append(card31)
    card32 = Card(name = "6", suit = "Clubs", value = 6, image = "https://deckofcardsapi.com/static/img/6C.png")
    cards.append(card32)
    card33 = Card(name = "7", suit = "Clubs", value = 7, image = "https://deckofcardsapi.com/static/img/7C.png")
    cards.append(card33)
    card34 = Card(name = "8", suit = "Clubs", value = 8, image = "https://deckofcardsapi.com/static/img/8C.png")
    cards.append(card34)
    card35 = Card(name = "9", suit = "Clubs", value = 9, image = "https://deckofcardsapi.com/static/img/9C.png")
    cards.append(card35)
    card36 = Card(name = "10", suit = "Clubs", value = 10, image = "https://deckofcardsapi.com/static/img/0C.png")
    cards.append(card36)
    card37 = Card(name = "J", suit = "Clubs", value = 11, image = "https://deckofcardsapi.com/static/img/JC.png")
    cards.append(card37)
    card38 = Card(name = "Q", suit = "Clubs", value = 12, image = "https://deckofcardsapi.com/static/img/QC.png")
    cards.append(card38)
    card39 = Card(name = "K", suit = "Clubs", value = 13, image = "https://deckofcardsapi.com/static/img/KC.png")
    cards.append(card39)
    # Diamond

    card40 = Card(name = "A", suit = "Diamonds", value = 1, image = "https://deckofcardsapi.com/static/img/AD.png")
    cards.append(card40)
    card41 = Card(name = "2", suit = "Diamonds", value = 2, image = "https://deckofcardsapi.com/static/img/2D.png")
    cards.append(card41)
    card42 = Card(name = "3", suit = "Diamonds", value = 3, image = "https://deckofcardsapi.com/static/img/3D.png")
    cards.append(card42)
    card43 = Card(name = "4", suit = "Diamonds", value = 4, image = "https://deckofcardsapi.com/static/img/4D.png")
    cards.append(card43)
    card44 = Card(name = "5", suit = "Diamonds", value = 5, image = "https://deckofcardsapi.com/static/img/5D.png")
    cards.append(card44)
    card45 = Card(name = "6", suit = "Diamonds", value = 6, image = "https://deckofcardsapi.com/static/img/6D.png")
    cards.append(card45)
    card46 = Card(name = "7", suit = "Diamonds", value = 7, image = "https://deckofcardsapi.com/static/img/7D.png")
    cards.append(card46)
    card47 = Card(name = "8", suit = "Diamonds", value = 8, image = "https://deckofcardsapi.com/static/img/8D.png")
    cards.append(card47)
    card48 = Card(name = "9", suit = "Diamonds", value = 9, image = "https://deckofcardsapi.com/static/img/9D.png")
    cards.append(card48)
    card49 = Card(name = "10", suit = "Diamonds", value = 10, image = "https://deckofcardsapi.com/static/img/0D.png")
    cards.append(card49)
    card50 = Card(name = "J", suit = "Diamonds", value = 11, image = "https://deckofcardsapi.com/static/img/JD.png")
    cards.append(card50)
    card51 = Card(name = "Q", suit = "Diamonds", value = 12, image = "https://deckofcardsapi.com/static/img/QD.png")
    cards.append(card51)
    card52 = Card(name = "K", suit = "Diamonds", value = 13, image = "https://deckofcardsapi.com/static/img/KD.png")
    cards.append(card52)

    return cards
    
    # number_cards = ['2', '3', '4', '5', '6', '7', '8', '9', '10']
    # face_cards = ['J', 'Q', 'K', 'A']
    # names = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
    # suits = ['Hearts', 'Diamonds', 'Clubs', 'Spades']

    # cards = []
    # value = 0

    # for number in range(13):
    #     if names[number] in number_cards:
    #         value = int(names[number])
    #     elif names[number] == "A":
    #         value = 1
    #     elif names[number] == "J":
    #         value = 11
    #     elif names[number] == "Q":
    #         value = 12
    #     elif names[number] == "K":
    #         value = 13
    #     card1 = Card(name = names[number], suit = suits[0], value = value)
    #     card2 = Card(name = names[number], suit = suits[1], value = value)
    #     card3 = Card(name = names[number], suit = suits[2], value = value)
    #     card4 = Card(name = names[number], suit = suits[3], value = value)
    #     cards.append(card1)
    #     cards.append(card2)
    #     cards.append(card3)
    #     cards.append(card4)
    
    # return cards
    
def create_tags():
    tags = []

    ace_high = Tag(name="Ace High", price=64)
    chip_collector = Tag(name="Chip Collector", price=32)
    bluff_master = Tag(name="Bluff Master", price=88)
    card_shark = Tag(name="Card Shark", price=19)
    pocket_rocket = Tag(name="Pocket Rocket", price=53)
    the_grinder = Tag(name="The Grinder", price=76)
    aggro_king_queen = Tag(name="Aggro King/Queen", price=42)
    math_whiz = Tag(name="Math Whiz", price=71)
    stone_cold = Tag(name="Stone Cold", price=27)
    final_table_regular = Tag(name="Final Table Regular", price=59)
    river_rat = Tag(name="River Rat", price=13)
    suited_connector = Tag(name="Suited Connector", price=82)
    bounty_hunter = Tag(name="Bounty Hunter", price=48)
    table_captain = Tag(name="Table Captain", price=95)
    live_wire = Tag(name="Live Wire", price=36)
    shark_bait = Tag(name="Shark Bait", price=68)
    satellite_specialist = Tag(name="Satellite Specialist", price=24)
    bubble_boy_bubble_girl = Tag(name="Bubble Boy/Bubble Girl", price=77)
    the_professor = Tag(name="The Professor", price=55)
    the_crusher = Tag(name="The Crusher", price=40)
    action_junkie = Tag(name="Action Junkie", price=61)
    quiet_assassin = Tag(name="Quiet Assassin", price=14)
    the_mathematician = Tag(name="The Mathematician", price=83)
    the_manipulator = Tag(name="The Manipulator", price=30)
    the_magician = Tag(name="The Magician", price=90)
    the_ice_man_ice_woman = Tag(name="The Ice Man/Ice Woman", price=70)
    the_sniper = Tag(name="The Sniper", price=21)
    the_technician = Tag(name="The Technician", price=44)
    the_puppet_master = Tag(name="The Puppet Master", price=75)
    the_silent_killer = Tag(name="The Silent Killer", price=39)
    the_oracle = Tag(name="The Oracle", price=50)
    the_maverick = Tag(name="The Maverick", price=86)
    the_strategist = Tag(name="The Strategist", price=18)
    the_high_roller = Tag(name="The High Roller", price=91)
    the_underdog = Tag(name="The Underdog", price=47)
    the_comeback_kid = Tag(name="The Comeback Kid", price=31)
    the_showman = Tag(name="The Showman", price=78)
    the_mind_reader = Tag(name="The Mind Reader", price=57)
    the_velvet_hammer = Tag(name="The Velvet Hammer", price=34)
    the_executioner = Tag(name="The Executioner", price=97)
    the_surgeon = Tag(name="The Surgeon", price=22)
    the_bankroll_builder = Tag(name="The Bankroll Builder", price=67)
    the_lone_wolf = Tag(name="The Lone Wolf", price=29)
    the_chameleon = Tag(name="The Chameleon", price=89)
    the_timekeeper = Tag(name="The Timekeeper", price=54)
    the_wild_card = Tag(name="The Wild Card", price=41)
    the_gamechanger = Tag(name="The Gamechanger", price=72)
    the_architect = Tag(name="The Architect", price=15)
    the_stealth_bomber = Tag(name="The Stealth Bomber", price=58)
    the_barracuda = Tag(name="The Barracuda", price=20)
    the_samurai = Tag(name="The Samurai", price=93)
    the_enigma = Tag(name="The Enigma", price=35)
    the_mentor = Tag(name="The Mentor", price=69)
    the_analyst = Tag(name="The Analyst", price=45)
    the_juggernaut = Tag(name="The Juggernaut", price=79)
    the_virtuoso = Tag(name="The Virtuoso", price=26)
    the_shadow = Tag(name="The Shadow", price=51)
    the_ghost = Tag(name="The Ghost", price=38)

    tags.append(ace_high)
    tags.append(chip_collector)
    tags.append(bluff_master)
    tags.append(card_shark)
    tags.append(pocket_rocket)
    tags.append(the_grinder)
    tags.append(aggro_king_queen)
    tags.append(math_whiz)
    tags.append(stone_cold)
    tags.append(final_table_regular)
    tags.append(river_rat)
    tags.append(suited_connector)
    tags.append(bounty_hunter)
    tags.append(table_captain)
    tags.append(live_wire)
    tags.append(shark_bait)
    tags.append(satellite_specialist)
    tags.append(bubble_boy_bubble_girl)
    tags.append(the_professor)
    tags.append(the_crusher)
    tags.append(action_junkie)
    tags.append(quiet_assassin)
    tags.append(the_mathematician)
    tags.append(the_manipulator)
    tags.append(the_magician)
    tags.append(the_ice_man_ice_woman)
    tags.append(the_sniper)
    tags.append(the_technician)
    tags.append(the_puppet_master)
    tags.append(the_silent_killer)
    tags.append(the_oracle)
    tags.append(the_maverick)
    tags.append(the_strategist)
    tags.append(the_high_roller)
    tags.append(the_underdog)
    tags.append(the_comeback_kid)
    tags.append(the_showman)
    tags.append(the_mind_reader)
    tags.append(the_velvet_hammer)
    tags.append(the_executioner)
    tags.append(the_surgeon)
    tags.append(the_bankroll_builder)
    tags.append(the_lone_wolf)
    tags.append(the_chameleon)
    tags.append(the_timekeeper)
    tags.append(the_wild_card)
    tags.append(the_gamechanger)
    tags.append(the_architect)
    tags.append(the_stealth_bomber)
    tags.append(the_barracuda)
    tags.append(the_samurai)
    tags.append(the_enigma)
    tags.append(the_mentor)
    tags.append(the_analyst)
    tags.append(the_juggernaut)
    tags.append(the_virtuoso)
    tags.append(the_shadow)
    tags.append(the_ghost)
    return tags

def create_icons():
    icons = []

    base_trunks = Icon(name = "Base Trunks", content = "https://sportshub.cbsistatic.com/i/2021/03/17/969ab4f3-5949-473b-974e-7b5831e69b89/future-trunks-future-trunks-meets-goku-1004356.jpg", price = 5)
    icons.append(base_trunks)
    kid_trunks = Icon(name = "Kid Trunks", content = "https://i1.sndcdn.com/artworks-000245017483-hx2ini-t500x500.jpg", price = 2)
    icons.append(kid_trunks)
    ssj_kid_trunks = Icon(name = "SSJ Kid Trunks", content = "https://dokkan.wiki/assets/global/en/character/card/1004440/card_1004440_character.png", price = 7)
    icons.append(ssj_kid_trunks)
    ssj_trunks = Icon(name = "SSJ Trunks", content = "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/05/super-saiyan-trunks.jpg", price = 10)
    icons.append(ssj_trunks)
    kid_goku = Icon(name = "Kid Goku", content = "https://i.redd.it/ekr3d36s2hs31.png", price = 5)
    icons.append(kid_goku)
    teen_goku = Icon(name = "Teen Goku", content = "https://static.wikia.nocookie.net/dragonuniverse/images/4/4c/Teen_Goku.png/revision/latest?cb=20171027214335", price = 10)
    icons.append(teen_goku)
    adult_goku = Icon(name = "Adult Goku", content = "https://images.immediate.co.uk/production/volatile/sites/3/2023/08/2023.06.28-06.20-boundingintocomics-649c79f009cdf-Cropped-8d74232.png?resize=768,574", price = 12)
    icons.append(adult_goku)
    ssj_goku = Icon(name = "SSJ Goku", content  = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4805bb10-2561-4f69-b899-a4f774a82de4/de5wfzx-2cddebcc-1784-4be1-8e5e-a8c1cbbcc5a5.png/v1/fill/w_1920,h_2560/goku__namek_saga__ssj___1__old_style_palette__by_ssjrose890_de5wfzx-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjU2MCIsInBhdGgiOiJcL2ZcLzQ4MDViYjEwLTI1NjEtNGY2OS1iODk5LWE0Zjc3NGE4MmRlNFwvZGU1d2Z6eC0yY2RkZWJjYy0xNzg0LTRiZTEtOGU1ZS1hOGMxY2JiY2M1YTUucG5nIiwid2lkdGgiOiI8PTE5MjAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.zH_bhNLnsP7L2WDqkpTW90_tOo9ffd8kX3jEj0tiE6M", price=20)
    icons.append(ssj_goku)
    ssj3_goku = Icon(name = "SSJ3 Goku", content = "https://static1.srcdn.com/wordpress/wp-content/uploads/2022/11/DBZ-SSJ3-Secret.jpg", price = 30)
    icons.append(ssj3_goku)
    ssj4_goku = Icon(name = "SSJ4 Goku", content = "https://static.wikia.nocookie.net/ultimate-dragon-story-site/images/c/c3/SSR_SSJ4_Goku_STR_HD.png/revision/latest?cb=20170820030033", price = 40)
    icons.append(ssj4_goku)
    ssj2_gohan = Icon(name = "SSJ2 Gohan", content = "https://www.themarysue.com/wp-content/uploads/2018/09/GohanSS2.jpg?fit=1200%2C675", price = 25)
    icons.append(ssj2_gohan)
    piccolo = Icon(name = "Piccolo", content = "https://static.wikia.nocookie.net/dragonball/images/c/c2/Piccolomanga.png/revision/latest/scale-to-width/360?cb=20160826150304", price = 15)
    icons.append(piccolo)

    girl_icon = Icon(name = "Girl default", content = "https://cdn2.vectorstock.com/i/1000x1000/98/11/girl-icon-flat-single-avatarpeaople-from-vector-14449811.jpg", price = 5)
    icons.append(girl_icon)
    boy_icon = Icon(name = "Boy default", content = "https://cdn-icons-png.flaticon.com/512/163/163801.png", price = 5)
    icons.append(boy_icon)
    sonic = Icon(name = "Sonic", content = 'https://drsw10gc90t0z.cloudfront.net/AcuCustom/Sitename/DAM/491/Sonic_the_Hedgehog.jpg', price = 10)
    icons.append(sonic)
    tails = Icon(name = "Tails", content = "https://i.kym-cdn.com/entries/icons/original/000/040/717/tails.jpeg", price = 7)
    icons.append(tails)
    mario = Icon(name = "Mario", content = "https://static.wikia.nocookie.net/ssb/images/3/3e/MPSS_Mario.png/revision/latest?cb=20220113043843", price = 10)
    icons.append(mario)
    luigi = Icon(name = "Luigi", content = "https://play.nintendo.com/images/Masthead_luigi.17345b1513ac044897cfc243542899dce541e8dc.9afde10b.png", price = 7)
    icons.append(luigi)
    
    mark_zuck = Icon(name = "Mark Zuckerberg", content = "https://cdn.britannica.com/98/236598-050-9F0C5A8D/Mark-Zuckerberg-2019.jpg", price = 10)
    icons.append(mark_zuck)
    elon_musk = Icon(name = "Elon Musk", content = "https://www.investopedia.com/thmb/XJDLdvCuNbcWk_EVZzXx84ae82c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1258889149-1f50bb87f9d54dca87813923f12ac94b.jpg", price = 10)
    icons.append(elon_musk)
    troll_face = Icon(name = "Troll", content = "https://upload.wikimedia.org/wikipedia/en/9/9a/Trollface_non-free.png", price = 30)
    icons.append(troll_face)
    return icons

if __name__ == '__main__':
    fake = Faker()
    with app.app_context():
        print("Starting seed...")
        # Seed code goes here!
        print("clearing db...")
        Card.query.delete()
        db.session.commit()
        User.query.delete()
        db.session.commit()
        Tag.query.delete()
        db.session.commit()
        Icon.query.delete()
        db.session.commit()
        UserIcon.query.delete()
        db.session.commit()
        UserTag.query.delete()
        db.session.commit()

        print("seeding tags... ")
        all_tags = create_tags()
        db.session.add_all(all_tags)
        db.session.commit()

        print("seedings icons...")
        all_icons = create_icons()
        db.session.add_all(all_icons)
        db.session.commit()

        print("seeding cards...")
        all_cards = create_cards()
        db.session.add_all(all_cards)
        db.session.commit()

        print("seeding usericons...")
        userIcon1 = UserIcon(user_id = 1, icon_id = 1)
        db.session.add(userIcon1)
        db.session.commit()

        print("seeding tags...")
        userTag1 = UserTag(user_id = 1, tag_id = 1)
        db.session.add(userTag1)
        db.session.commit()
