"""added emote model and added relationship for emote and user

Revision ID: fc724b1a87d1
Revises: f8b56b7f5f57
Create Date: 2024-04-06 16:26:42.171238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc724b1a87d1'
down_revision = 'f8b56b7f5f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useremotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emote_id'], ['emotes.id'], name=op.f('fk_useremotes_emote_id_emotes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_useremotes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useremotes')
    op.drop_table('emotes')
    # ### end Alembic commands ###
