"""added user and icon relationship, user and tag relationship

Revision ID: fd0125c2f6d0
Revises: dca5f2225492
Create Date: 2024-03-20 08:15:48.057647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0125c2f6d0'
down_revision = 'dca5f2225492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usericons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icons.id'], name=op.f('fk_usericons_icon_id_icons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usericons_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_usertags_tag_id_tags')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usertags_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('icons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_icons_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tags_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_tags_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('icons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_icons_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_table('usertags')
    op.drop_table('usericons')
    # ### end Alembic commands ###
